var friendAge=[15,17,14,16];
var sonaliAge=friendAge[2];
friendAge[1]=21;
var position=friendAge.indexOf(141);
friendAge.push(15);
console.log(position);
console.log(friendAge);
friendAge.push(19);
console.log(friendAge);
console.log(friendAge.length);
friendAge.pop();
console.log(friendAge);
friendAge.unshift(12);
console.log(friendAge);
friendAge.shift();
console.log(friendAge);