<?php
SELECT * FROM CUSTOMER;
SELECT count(*) as TOTAL, CITY FROM CUSTOMER GROUP BY CITY;
SELECT * FROM `CUSTOMER` WHERE City='Salam' AND POSTAL_CODE='03079';
SELECT * FROM `CUSTOMER` WHERE (City='Salam' AND POSTAL_CODE='03079') OR City = 'Wilmington';
SELECT * FROM `CUSTOMER` WHERE (CITY='Salem' AND POSTAL_CODE IN('03000','03079') OR CITY='Wilmington' AND POSTAL_CODE='0186');
SELECT CUSTOMER.CUST_ID, CUSTOMER.CITY, INDIVIDUAL.BIRTH_DATE, INDIVIDUAL.FIRST_NAME, INDIVIDUAL.LAST_NAME, CUSTOMER.POSTAL_CODE FROM CUSTOMER, INDIVIDUAL WHERE CITY='Salem' AND CUSTOMER.CUST_ID = INDIVIDUAL.CUST_ID ;

?>