<?php
SELECT * FROM CUSTOMER;
SELECT count(*) as TOTAL, CITY FROM CUSTOMER GROUP BY CITY;
SELECT COUNT(*)as TOTAL_CUSTOMERS,CITY,STATE,POSTAL_CODE FROM CUSTOMER GROUP BY CITY,POSTAL_CODE;
SELECT * FROM CUSTOMER Where City = 'Salem';
SELECT * FROM `CUSTOMER` WHERE City='Salem' AND POSTAL_CODE='03079';
SELECT * FROM `CUSTOMER` WHERE City='Salem' AND POSTAL_CODE='03079' OR City='Wilmington';
SELECT * FROM `CUSTOMER` WHERE (City='Salem' AND POSTAL_CODE='03079') OR City = 'Wilmington';
SELECT * FROM `CUSTOMER` WHERE City='Salem' AND POSTAL_CODE IN('03000','03079') OR City='Wilmington';
SELECT * FROM `CUSTOMER` WHERE (CITY='Salem' AND POSTAL_CODE IN('03000','03079') OR CITY='Wilmington' AND POSTAL_CODE='01887');
SELECT * FROM CUSTOMER, INDIVIDUAL WHERE CITY='Salem' AND CUSTOMER.CUST_ID=INDIVIDUAL.CUST_ID;
SELECT CUSTOMER.CUST_ID,CUSTOMER.CITY, INDIVIDUAL.BIRTH_DATE,INDIVIDUAL.FIRST_NAME,INDIVIDUAL.LAST_NAME,CUSTOMER.POSTAL_CODE FROM CUSTOMER, INDIVIDUAL WHERE CITY='Salem' AND CUSTOMER.CUST_ID=INDIVIDUAL.CUST_ID;

SELECT CUSTOMER.CUST_ID,CUSTOMER.CITY, INDIVIDUAL.BIRTH_DATE,INDIVIDUAL.FIRST_NAME,INDIVIDUAL.LAST_NAME,CUSTOMER.POSTAL_CODE FROM CUSTOMER JOIN INDIVIDUAL ON CUSTOMER.CUST_ID=INDIVIDUAL.CUST_ID WHERE CITY='Salem';

Select SUM(AVAIL_BALANCE), CUST_ID FROM ACCOUNT GROUP BY CUST_ID;

Select SUM(AVAIL_BALANCE), CUST_ID,OPEN_BRANCH_ID FROM ACCOUNT GROUP BY CUST_ID,OPEN_BRANCH_ID;
Select SUM(AVAIL_BALANCE) FROM ACCOUNT GROUP BY CUST_ID;
Select SUM(AVAIL_BALANCE) as total FROM ACCOUNT GROUP BY CUST_ID;
Select CUST_ID,OPEN_BRANCH_ID, SUM(AVAIL_BALANCE) as total FROM ACCOUNT GROUP BY CUST_ID,OPEN_BRANCH_ID;
Select CUST_ID, SUM(AVAIL_BALANCE) as total FROM ACCOUNT GROUP BY CUST_ID HAVING total>5000;
SELECT * FROM (Select CUST_ID, SUM(AVAIL_BALANCE) as total FROM ACCOUNT GROUP BY CUST_ID)as balance WHERE total>5000 ;
Select account.CUST_ID, SUM(AVAIL_BALANCE),FIRST_NAME,LAST_NAME,BIRTH_DATE as total FROM ACCOUNT,individual WHERE individual.CUST_ID=account.CUST_ID GROUP BY CUST_ID HAVING total>5000;
Select account.CUST_ID, SUM(AVAIL_BALANCE) as total,FIRST_NAME,LAST_NAME,BIRTH_DATE FROM ACCOUNT,individual WHERE individual.CUST_ID=account.CUST_ID GROUP BY CUST_ID HAVING total>5000;
Select account.CUST_ID, SUM(AVAIL_BALANCE) as total,FIRST_NAME,LAST_NAME,BIRTH_DATE FROM ACCOUNT JOIN individual on individual.CUST_ID=account.CUST_ID HAVING total>5000;
Select account.CUST_ID, SUM(AVAIL_BALANCE) as total,FIRST_NAME,LAST_NAME,BIRTH_DATE,OPEN_BRANCH_ID FROM ACCOUNT 
JOIN individual on individual.CUST_ID=account.CUST_ID 
JOIN branch on branch.BRANCH_ID=account.OPEN_BRANCH_ID
GROUP BY account.CUST_ID,account.OPEN_BRANCH_ID;
Select account.CUST_ID, SUM(AVAIL_BALANCE) as total,FIRST_NAME,LAST_NAME,BIRTH_DATE,OPEN_BRANCH_ID,branch.ADDRESS FROM ACCOUNT 
JOIN individual on individual.CUST_ID=account.CUST_ID 
JOIN branch on branch.BRANCH_ID=account.OPEN_BRANCH_ID
GROUP BY account.CUST_ID,account.OPEN_BRANCH_ID;


?>