<?php
$fruits=array("apple","banna","orange","plum","dates","mange");
$ramdom=[
    "a"=>12,
    "b"=>13,
    "c"=>31,
    "d"=>45,
    12=>24,
    "e"=>25,
    "f"=>78
];
$newFruits1=array_slice($fruits,0,3);
$newFruits2=array_slice($fruits,3,null,true);
$newFruits=array_merge($newFruits1,$newFruits2);
print_r($newFruits1);
print_r($newFruits2);
print_r($newFruits);
$newFruitsPlus=$newFruits1+$newFruits2;
print_r($newFruitsPlus);
?>